import Link from "next/link";
import { FileText, Plus } from "lucide-react";
import { deletePost } from "@/app/(protected)/admin/blog/actions";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { prisma } from "@/lib/prisma";

export default async function BlogAdminPage() {
  const posts = await prisma.post.findMany({ orderBy: { updatedAt: "desc" }, select: { id: true, title: true, slug: true, status: true, readingTime: true, updatedAt: true, categories: { select: { name: true } } } });
  return <div className="space-y-6 p-5 sm:p-8 lg:p-10"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold uppercase tracking-[.16em] text-sky-300">CMS</p><h1 className="mt-2 text-3xl font-semibold text-white sm:text-4xl">Blog posts</h1><p className="mt-2 text-sm text-slate-400">Create, publish, and maintain VJtronix articles.</p></div><Link className="inline-flex items-center justify-center gap-2 rounded-lg bg-sky-300 px-3 py-2 text-sm font-semibold text-slate-950 hover:bg-sky-200" href="/admin/blog/new"><Plus className="size-4" />New post</Link></div><Card><CardHeader><CardTitle>All posts</CardTitle><CardDescription>{posts.length} post{posts.length === 1 ? "" : "s"} in the CMS.</CardDescription></CardHeader><CardContent>{posts.length === 0 ? <div className="grid min-h-48 place-items-center rounded-lg border border-dashed border-white/15 text-center"><div><FileText className="mx-auto size-6 text-slate-500" /><p className="mt-3 text-sm text-slate-500">No posts yet. Create your first article.</p></div></div> : <ul className="divide-y divide-white/10">{posts.map((post) => <li className="flex flex-col gap-3 py-4 first:pt-0 sm:flex-row sm:items-center sm:justify-between" key={post.id}><div><p className="font-medium text-slate-200">{post.title}</p><p className="mt-1 text-xs text-slate-500">/{post.slug} · {post.readingTime} min read · {post.categories.map((c) => c.name).join(", ") || "Uncategorized"}</p></div><div className="flex items-center gap-3"><span className={post.status === "PUBLISHED" ? "text-xs text-emerald-200" : "text-xs text-amber-200"}>{post.status}</span><Link className="text-sm font-medium text-sky-200 hover:text-sky-100" href={`/admin/blog/${post.id}`}>Edit</Link><form action={deletePost.bind(null, post.id)}><button className="text-sm text-rose-200 hover:text-rose-100" type="submit">Delete</button></form></div></li>)}</ul>}</CardContent></Card></div>;
}
